name: "go-rookie"
mode: "dev"
port: 8084
log:
  level: "debug"
  filename: "log/go-rookie.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host:
  port:
  user:
  password:
  dbname:
  max_open_connection:
  max_idle_connection:
redis:
  host:
  password:
  port:
  db:
  pool_size: